vich_uploader:
    db_driver: orm

    mappings:
        photos:
            uri_prefix: /image/photos
            upload_destination: '%kernel.project_dir%/public/image/photos'
        cvs:
            uri_prefix: /cv/cvs
            upload_destination: '%kernel.project_dir%/public/cv/cvs'
        ribs:
            uri_prefix: /rib/ribs
            upload_destination: '%kernel.project_dir%/public/rib/ribs'
        sliders:
            uri_prefix: /image/sliders
            upload_destination: '%kernel.project_dir%/public/image/sliders'
