vich_uploader:
    db_driver: orm

    mappings:
        affiche_config:
            uri_prefix: /img/affiches
            upload_destination: '%kernel.project_dir%/public/img/affiches'
        portrait_config:
            uri_prefix: /img/portraits
            upload_destination: '%kernel.project_dir%/public/img/portraits'
        
