vich_uploader:
    db_driver: orm

    mappings:
        categories:
            uri_prefix: /images/categories
            upload_destination: '%kernel.project_dir%/public/images/categories'
        ventes:
            uri_prefix: /images/ventes
            upload_destination: '%kernel.project_dir%/public/images/ventes'


